### ISSUE TITLE
Manifest specs

### ISSUE THREAD

**Issue by xristy** [buda-base/volume-manifest-builder#1]
See [Manifest for Volume](https://docs.google.com/document/d/1bfCWh6D_Eh0WqOmwLxyXjot6ckfV7i_FBs0-3NWbOo8/edit#) for notes on how the current minimal manifest may be expected to evolve

**Comment by jimk-bdrc** [comment]
Is this issue still relevant? The document looks incomplete. Also, the current file-based manifest as we have it has no representation of order. Just filename and size.

**Comment by eroux** [comment]
let's ignore it, the manifest will be a separate file
