### ISSUE TITLE
W20869 doesn't create manifest correctly

### ISSUE THREAD

**Issue by jimk-bdrc** [buda-base/volume-manifest-builder#28]
Discovered by [archive-ops-134](https://github.com/buda-base/archive-ops/issues/134) by @eroux.  When retried, got the same results as the OP.

**Comment by jimk-bdrc** [comment]
This is because volume-manifest-tool failed to retrieve a BOM (fileList.json) from the S3 resource. It should have then just got the file list from an s3 list_entries call, but it wasn't doing that.

**Comment by jimk-bdrc** [comment]
[IIIF Viewer for W20869 shows the works](https://library.bdrc.io/show/bdr:W20869)

**Comment by xristy** [comment]
When I visit the link. click on the scan page image, scroll down a bit, then It seems the manifest is loaded for vol 1 - 4 and then loading is stalled indefinitely for me:

![Screen Shot 2020-07-31 at 7 57 39 PM](https://user-images.githubusercontent.com/3542294/89090431-79b22900-d368-11ea-85cf-fb71074e4e3f.png)

is this a manifest problem or something else?

**Comment by jimk-bdrc** [comment]
I did some more testing and confirmed your findings. this bug is still
present. It’s a volume by volume thing. I’m looking at it some more today.

**Comment by jimk-bdrc** [comment]
@xristy @eroux 
I regenerated W20869. All the dimensions.json files are fully populated. I still can't get beyond volume4, just like Chris can't.  I uploaded the dimensions.json of the fifth volume (assuming they're in order from `W20869-0334`)

[0338dims.json.txt](https://github.com/buda-base/volume-manifest-tool/files/5010991/0338dims.json.txt)

It seems to be correct. 
I'll regenerate all the missing volumes. Plz advise if you need more json samples.

**Comment by eroux** [comment]
Thanks! It seems to work fine now! I restarted the server, I'll look in to the bug that lead to the server being stalled on Monday. The person who reported the problem said this was relatively common, I'll tell you if more examples are reported... but it should all get detected by https://github.com/buda-base/archive-ops/issues/134 anyways.

**Comment by jimk-bdrc** [comment]
@eroux @xristy [W00EGS1016299](https://library.bdrc.io/show/bdr:W00EGS1016299)  is having the same issue, even though its BOMS are all good, at least according to their size:
[W00EGS1016299.dimensions.zip](https://github.com/buda-base/volume-manifest-tool/files/5011083/W00EGS1016299.dimensions.zip)

**Comment by jimk-bdrc** [comment]
Closed by Pull Request #29
