### ISSUE TITLE
Relate to [IIIF 57 CMYK](https://github.com/buda-base/buda-iiif-server/issues/57)

### ISSUE THREAD

**Issue by jimk-bdrc** [buda-base/volume-manifest-builder#30]
1. Create tickets for audit tool.
2. Have this ticket own the audit process for existing web material.
3. Write a separate ticket for volume-manifest-builder

**Comment by TBRC-Travis** [comment]
@jimk-bdrc See the discussion between Elie and I [here](https://github.com/buda-base/buda-iiif-server/issues/57).  For now I think we'll only want to worry about audit tool.

**Comment by jimk-bdrc** [comment]
@eroux @TBRC-Travis it would be simple enough to mark it in `dimensions.json` with the file mode [PIL documentation](https://pillow.readthedocs.io/en/3.0.x/handbook/concepts.html?highlight=color space)

**Comment by jimk-bdrc** [comment]
@eroux should the CMYK color space be a warning, or an error in audit tool?

**Comment by eroux** [comment]
hmm good question for the warn vs error... I don't have a strong opinion on that, I think both are good.

Yes, I think indicating the mode when it's CMYK would be good. I think it's best not to indicate the mode on each image when it's the expected one, meaning:
- for `.jpg` when it's `L` or  `RGB`
- for `.tif` when it's `1`

I sort of remember that at some point the code of the tool was writing this PIL mode but I'm not 100% sure...

**Comment by jimk-bdrc** [comment]
Yes, [this change](https://github.com/buda-base/volume-manifest-builder/commit/6e8ec3a89287ddcc9b705179c55dd191ae06df3b) shows you relocated pilmode, but it was still very conditional.

**Comment by jimk-bdrc** [comment]
Discuss with @TBRC-TimB in 2021

**Comment by jimk-bdrc** [comment]
buda-base/buda-iiif-server#57 is closed, so there's no need for this.
