### ISSUE TITLE
Volume Manifest Builder to use local file system

### ISSUE THREAD

**Issue by jimk-bdrc** [buda-base/volume-manifest-builder#34]
v-m-b gets its images for processing from S3. We would like to use the local file system for two reasons:
- we can generate manifest.jsons during the sync process, instead of a post-processing step
- we eliminate the cost of calling S3's `GetObject` for each image.
- Should be faster

**Comment by jimk-bdrc** [comment]
@eroux @xristy I'd like to extend this issue a little by proposing we not look for and save graphics errors any more.  rationales:
1. Modular - this code should only build the volume manifest. Error checking is an add-on 
1. audit-tool is the definitive source of format errors, it has better user control. This code uses magic constants which no longer apply.
1. The original code created a csv error file on each invocation, even if no errors were found. Let's not do that anymore.

If you want an informal notification of errors, I could leave the error checking code in place, but have the output added to the json, if it would not interfere with iiif. I could add an array:
{
   "filename" : "IMG12345.jpg",
   "dimensions" : { height: 42 , width: 42 },
    graphics_errors : [
             "imgTooBig",
             "notTif4",
              "notgreyscale"]
}

But mostly I think there's no market for this output.  
Thoughts? Add it to json, or just drop it?

Third thought, v-m-b can just add the raw data, without the judgement (and add the dpi requested in    #33 )
{....
graphics_attribs: 
    { filesize : 403424,
      format : TIFF , 
      compression : LZW , 
      monochrome:  true,
      resolution_dpi : 300
    }
...
}

**Comment by eroux** [comment]
Well, I agree with the principle yes... the tool already writes a "size" property in the json when the image is too big, which is the main thing I need for iiif. The csv is only about gathering some info about non-conforming images, if it's deemed useless it can go.

**Comment by jimk-bdrc** [comment]
No it doesn't.

**Comment by jimk-bdrc** [comment]
I understand, thanks. I'll dump the errors, but will add the resolution in another change.

**Comment by xristy** [comment]
Assuming the Audit tool is run prior to generating the dimensions.json then the error checking in v-m-b shouldn't find any but if it does then it would be useful to know about it. Not checking is won't make errors go away. FInding an error early can reduce debug effort later
