### ISSUE TITLE
/W8LS73712-I8LS73716 failed build

### ISSUE THREAD

**Issue by jimk-bdrc** [buda-base/volume-manifest-builder#39]
8:21 AM (2 hours ago)
	
to me
No manifest created for /Users/tbrc/staging/sync2archive/W8LS73712-I8LS73716

**Comment by TBRC-Travis** [comment]
@jimk-bdrc there's a pretty straightforward reason for this error.  W8LS73712-I8LS73716 and W8LS73712-I8LS73717 have no images.  I thought I downloaded the updated version of manifestForWork which would handle this situation properly, but maybe not.  how do I determine if I'm running the correct version?

**Comment by TBRC-Travis** [comment]
@jimk-bdrc I double-checked and I do have bdrc-volume-manifest-builder version 1.1.2 installed so this seems to expected behavior.  I think we just need to change the "ERROR in local_v_m_b" message to be a warning instead.

**Comment by jimk-bdrc** [comment]
Will be fixed with #40
