### ISSUE TITLE
Trigger warning notification for volumes with no images

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/volume-manifest-builder#40]
Currently v-m-b generates an error message when there is no manifest created for empty volumes.  This should trigger a warning notification.  Ideally this should be aggregated together into a single notification if there are multiple volumes in a work that have no images.

**Comment by jimk-bdrc** [comment]
Fixed in #38, in change dae7d44722d5b29ded0ffebd92b169e862defb63
