### ISSUE TITLE
Additional error log output during manifest creation

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/volume-manifest-builder#41]
Encountered an error when running manifestForWork on W28882 where the image group folder (W28882-4784) didn't match the image group record in the database (W28882-I4784).  The only error generated in the log was:

local_v_m_b-ERROR: No manifest created for W28882-I4784

It would be great if, in addition to this output, v_m_b could also specify that the image group folder could not be found, or that there's a mismatch (in this case between W28882-4784 and W28882-I4784

**Comment by jimk-bdrc** [comment]
[2021-01-25_15_35_28818.local_v_m_b.log.txt](https://github.com/buda-base/volume-manifest-builder/files/5869573/2021-01-25_15_35_28818.local_v_m_b.log.txt)
This log shows the capacity is there. The complete text of the log message and exception stack are captured in the log.
