### ISSUE TITLE
NPL works fail during sync

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/volume-manifest-builder#45]
Fails during dimensions manifest generation with this error:

```
    building W1NPL109 dimensions manifest for BUDA
ERROR - Could not find image groups for /Users/tbrc/staging/sync2archive/W1NPL109
```

[2021-02-17_21_22_4651.local_v_m_b.log](https://github.com/buda-base/volume-manifest-builder/files/6004520/2021-02-17_21_22_4651.local_v_m_b.log)

These works don't have tbrc.org database records as the tech team only configured NPL works for BUDA.

**Comment by jimk-bdrc** [comment]
have volume-manifest-builder use http://purl.bdrc.io/query/table/volumesForInstance?R_RES=bdr:WORKWHATEVER&format=json

**Comment by TBRC-Travis** [comment]
Installed the new version of bdrc-volume-manifest-builder (1.1.4) and ran manifestForWork on the NPL works.  It's now working.  Thanks!

**Comment by eroux** [comment]
Excellent, thanks! Are the other unsynced works in this collection?

**Comment by TBRC-Travis** [comment]
There's only one more we haven't synced yet - W1NPL166 - which needs some more work.  Will let you know when that's done.

**Comment by jimk-bdrc** [comment]
Reopening to change request format to XML
