### ISSUE TITLE
Change v_m_b log file name

### ISSUE THREAD

**Issue by jimk-bdrc** [buda-base/volume-manifest-builder#59]
@TBRC-Travis requests buildManifestForWork-2022-05-27_09.23.07.txt rather than 2022-05-27_09.23.07-local_v_m_b.log

Use a camel cased figure with the name first.

@jimk-bdrc notes
- this can be run in parallel, so add process id.
-  we may want to aggregate runs on different hosts, so add machine name.
- Can this be parameterized, so someone can set an environment variable to specify the format, something like `{processName}-YYYY-mm-DD-HH_MM_SS-[pid]-host.ext` where ext can be anything you want? (logs should remain .log, to distinguish them from text, docs, and lists, but allowing an override is still a good idea.)

**Comment by TBRC-Travis** [comment]
thanks @jimk-bdrc!  I particularly like the parameterized/override option.  great idea.
